language: generic
sudo: required
services:
  - docker
  
before_install:
  - docker build -t nachis/react-test -f ./client/Dockerfile.dev ./client
  
script:
  - docker run -e CI=true nachis/react-test npm test
  
after_success:
  - docker build -t nachis/multi-client ./client
  - docker build -t nachis/multi-nginx ./nginx
  - docker build -t nachis/multi-server ./server
  - docker build -t nachis/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push nachis/multi-client
  - docker push nachis/multi-nginx
  - docker push nachis/multi-server
  - docker push nachis/multi-worker